### ISSUE TITLE
Update obsolete autoconf version

### ISSUE THREAD

**Issue by mans0954** [ScientificWord/mozilla#6]
Currently `configure.in` targets autoconf 2.13 which is obsolete:

https://github.com/ScientificWord/mozilla/blob/d949d9926f40f2b3ba8183b579c5c17391deb2dc/configure.in#L63

Please update `configure.in` to work with 2.69 or higher.

Thank you.

**Comment by Barry-MacKichan** [comment]
For a very long time, the Mozilla instructions for setting up a build environment said to install *autoconf 2.13* specifically. The problem this avoided seems to be that *autoconf* was changed at that time to disable conditional checks, and Mozilla chose to stick with 2.13 rather than make (what seem to be extensive) changes to their configure scripts. You can read some of the discussion at https://bugzilla.mozilla.org and searching for bug 104642.
It's not clear to me how the current Mozilla builds avoid this problem, but it seems to me that they stuck with using *autoconf 2.13* until they went to using Python for managing builds. This would mean they never changed *configure.in* to be used with later versions of *autoconf*.
My position is that we should continue using 2.13 until we upgrade our build system to the one Mozilla is using now. That may or may not ever happen.
